---
title: "Dyerlab Teaching"
date: "25 August 2022"
author: 
- name: Rodney J. Dyer
  url: https://dyerlab.org
  affiliation: Center for Environmental Studies
  affiliation_url: https://ces.vcu.edu
  orcid_id: 0000-0003-4707-3453
format: 
  html:
    standalone: true
    self-contained: true
    full-width: true
    toc: true
---



> This github account houses all of the repositories I have created for teaching resources.  Where possible, I have attempted to break apart the components of my instruction into the least common denominators.  These can individually serve as building-blocks of instruction for a wide range of coureses as well as sources of quick instruction for individuals needing to relearn specific components.


##  Syllabi

- [ENVS 543: Environmental Data Literacy](https://github.com/dyerlabteaching/ENVS543)
- [2 day Data Literacy Workshop]()
- [Landscape Genetics]()


## Logistics Lectures

- [Welcome & Logistics](https://dyerlabteaching.github.io/Welcome/slides.html#/title-slide)  
- [Github]()  
- [Markdown]()  
- [R Environment]()
- [Xaringan Slides]()

## R Grammar Lectures

- [Character Data]()
- [Data Frames]()
- [Data Types]()
- [Data Containers]()
- [Dates]()
- [Factor Data]()
- [Numerical Data]()
- [Tidyverse]()

## Data Manipulation

- [Functions]()
- [Relational Data]()
- [Data Manipulation - Old School]()
- [Data Manipualtion - Tidyverse]()

## Visualization

- [Basic Visualization]()
- [GGPlot]()
- [Leaflet Maps]()

## Analysis Lectures

- [Binomial]()
- [Inferences on a Mean]()
- [Categorical ~ f( Categorical )]()
- [Categorical ~ f( Continuous )]()
- [Continuous ~ f( Categorical )]()
- [Continuous ~ f( Continuous )]()
- [Network Models]()
- [Ordination]()
- [Resistance Models]()


## Spatial Lectures

- [Cartography]()
- [Census Data]()
- [Habitat Analyses]()
- [Points, Lines, & Polygons]()
- [Rasters]()
- [Raytracing]()

## Genetics

- [Genetic Diversity]()
- [Population Genetics Processes]()
- [Spatial Genetic Structure]()
- [Population Subdivision]()
